// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRuDP359ijY2Bdrsazb8qG1iMpICNqkR0',
    appId: '1:181302113709:web:0f767b8c62c372c56c5d24',
    messagingSenderId: '181302113709',
    projectId: 'project-graduate-chatbot',
    authDomain: 'project-graduate-chatbot.firebaseapp.com',
    storageBucket: 'project-graduate-chatbot.firebasestorage.app',
    measurementId: 'G-8W09HYNF76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWdQISGNDcwERSt0wl3jAIHLlGarbRLK8',
    appId: '1:181302113709:android:7860471f7e2407606c5d24',
    messagingSenderId: '181302113709',
    projectId: 'project-graduate-chatbot',
    storageBucket: 'project-graduate-chatbot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcqsGlyZd5ULlVhKwlYPOaCbGSwos3BYo',
    appId: '1:181302113709:ios:83a1eadd9571a64f6c5d24',
    messagingSenderId: '181302113709',
    projectId: 'project-graduate-chatbot',
    storageBucket: 'project-graduate-chatbot.firebasestorage.app',
    iosBundleId: 'com.example.dahcpplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcqsGlyZd5ULlVhKwlYPOaCbGSwos3BYo',
    appId: '1:181302113709:ios:83a1eadd9571a64f6c5d24',
    messagingSenderId: '181302113709',
    projectId: 'project-graduate-chatbot',
    storageBucket: 'project-graduate-chatbot.firebasestorage.app',
    iosBundleId: 'com.example.dahcpplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRuDP359ijY2Bdrsazb8qG1iMpICNqkR0',
    appId: '1:181302113709:web:faf614490211089a6c5d24',
    messagingSenderId: '181302113709',
    projectId: 'project-graduate-chatbot',
    authDomain: 'project-graduate-chatbot.firebaseapp.com',
    storageBucket: 'project-graduate-chatbot.firebasestorage.app',
    measurementId: 'G-ME162BBZ09',
  );
}
